### ISSUE TITLE
File picker not populating data when initiated through jquery onchange event(second time)

### ISSUE THREAD

**Issue by jyothicoder** [hazzardweb/filepicker-docs#3]
Hi,
we bought this plugin and implemented in laravel. I am using a select drop down which displays list of items. on change of a item i am displaying appropriate results.
First time on change event is working fine and results are getting populated. but for the other  on change requests, the filepickercontroller is returning the correct results but those are not appending to files list.

Please help me.

**Comment by cretueusebiu** [comment]
You'll have to use the [fetch](http://docs.hazzardweb.com/filepicker/2.0/apijs#fetch) method and then trigger a [load](http://docs.hazzardweb.com/filepicker/2.0/ui#load) event:

```javascript
// Get the filepicker instance
var FP = $('#filepicker').filePicker() 

// Fetch files from server
FP.fetch({ some_param: 'some_value' })
  .done(function (result) {
    // Clear previous files
    $('.files').html('') 

    // Trigger load event with the result 
    FP.trigger('load', null, result) 
  })
```

**Comment by jyothicoder** [comment]
Hi, 
Thank you for your response.
As I already mentioned, it is fetching files from server. but It is not appending to files list (".files"). when I manually modify the renderdownload method in filepicker-ui.js by changing the below line, it is appending.
change  _this6.options.ui.filesList.append(file.context); to $(".files").append(file.context);

but the pagination and delete are not working when I do like this.

**Comment by cretueusebiu** [comment]
Could you maybe send me a link to your app privately via CodeCanyon ? Or maybe an example of your app ?

**Comment by kiranmai28mv** [comment]
Hi. when using fetch and triggering load I am able to load the results inside files. But the thing is pagination is not applied on the result. and how to send updated request parameters to upload and crop of the filepicker.
