### ISSUE TITLE
changing the dimensions of image after upload

### ISSUE THREAD

**Issue by kiranmai28mv** [hazzardweb/filepicker-docs#5]
Dear,
Kindly let me know the procedure for keeping the same dimensions to all images after uploading and cropping.

thanks

**Comment by cretueusebiu** [comment]
You can keep the original image using the [keep_original_image](http://docs.hazzardweb.com/filepicker/2.0/configphp#keep_original_image) option or  for image versions using [image_versions..raw](http://docs.hazzardweb.com/filepicker/2.0/configphp#raw).
